version: "3"
services:
    frontend:
        container_name: web
        build:
            context: ./client
            dockerfile: Dockerfile
        image: renvieir/web
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: renvieir/server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/app